// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    'IconAkarIcons:triangleRight': typeof import('~icons/akar-icons/triangle-right')['default']
    'IconBx:bxsDish': typeof import('~icons/bx/bxs-dish')['default']
    'IconBxs:dish': typeof import('~icons/bx/s-dish')['default']
    'IconCib:adguard': typeof import('~icons/cib/adguard')['default']
    'IconFaSolid:chalkboardTeacher': typeof import('~icons/fa-solid/chalkboard-teacher')['default']
    'IconFaSolid:ellipsisV': typeof import('~icons/fa-solid/ellipsis-v')['default']
    'IconFluent:arrowRightBoldCircle': typeof import('~icons/fluent/arrow-right-bold-circle')['default']
    'IconFluent:arrowsBidirectional24Regular': typeof import('~icons/fluent/arrows-bidirectional24-regular')['default']
    'IconFluent:dataTrending16Filled': typeof import('~icons/fluent/data-trending16-filled')['default']
    'IconFluent:peopleTeam16Filled': typeof import('~icons/fluent/people-team16-filled')['default']
    'IconIon:bed': typeof import('~icons/ion/bed')['default']
    'IconLa:language': typeof import('~icons/la/language')['default']
    'IconMdi:arrowLeftBoldCircle': typeof import('~icons/mdi/arrow-left-bold-circle')['default']
    'IconMdi:arrowLeftDropCircleOutline': typeof import('~icons/mdi/arrow-left-drop-circle-outline')['default']
    'IconMdi:arrowRightBoldCircle': typeof import('~icons/mdi/arrow-right-bold-circle')['default']
    'IconMdi:arrowRightDropCircleOutline': typeof import('~icons/mdi/arrow-right-drop-circle-outline')['default']
    'IconMdi:githubFace': typeof import('~icons/mdi/github-face')['default']
    'IconMdi:signalCellular3': typeof import('~icons/mdi/signal-cellular3')['default']
    'IconMdi:signalCullular3': typeof import('~icons/mdi/signal-cullular3')['default']
    'IconPh:sunDimBold': typeof import('~icons/ph/sun-dim-bold')['default']
    'IconRi:alarmWarningFill': typeof import('~icons/ri/alarm-warning-fill')['default']
    'IconRi:database2Fill': typeof import('~icons/ri/database2-fill')['default']
    'IconSimpleIcons:gitee': typeof import('~icons/simple-icons/gitee')['default']
    'IconSimpleIcons:nuxtdotjs': typeof import('~icons/simple-icons/nuxtdotjs')['default']
    'IconTeenyicons:bedSingleSolid': typeof import('~icons/teenyicons/bed-single-solid')['default']
    'IconTeenyicons:textDocumentAltSolid': typeof import('~icons/teenyicons/text-document-alt-solid')['default']
    'IconUil:angleDown': typeof import('~icons/uil/angle-down')['default']
    'IconUil:apps': typeof import('~icons/uil/apps')['default']
    'IconUil:bars': typeof import('~icons/uil/bars')['default']
    'IconUil:clock': typeof import('~icons/uil/clock')['default']
    'IconUil:laptop': typeof import('~icons/uil/laptop')['default']
    'IconUil:moon': typeof import('~icons/uil/moon')['default']
    'IconUil:sun': typeof import('~icons/uil/sun')['default']
    'IconUil:times': typeof import('~icons/uil/times')['default']
    'IconUiw:date': typeof import('~icons/uiw/date')['default']
  }
}

export { }
